export const TEST_MUTATION = 'TEST_MUTATION'
export const SET_PROJECT_MUTATION = 'SET_PROJECT_MUTATION'
export const ADD_ERROR_LOG_MUTATION = 'ADD_ERROR_LOG_MUTATION'
export const CHANGE_MENU_INDEX_MUTATION = 'CHANGE_MENU_INDEX_MUTATION'
